#!/usr/bin/env perl
$nm=$ARGV[0];
if(@ARGV > 1) { 
	$nnodes=$ARGV[1];
}
else { $nnodes=1; } 

$nprocs=16*$nnodes;

print "
#PBS -q normal
#PBS -A TG-CDA100010
#PBS -l nodes=$nnodes:ppn=16
#PBS -l walltime=1:00:00
#PBS -N $nm
#PBS -e \$PBS_JOBID.err
#PBS -o \$PBS_JOBID.out
#PBS -m bea
#PBS -M ywu27\@illinois.edu

# . /etc/profile.d/modules.sh
module load intel mvapich2_ib vasp

cd \$PBS_O_WORKDIR

mpirun_rsh -export -hostfile \$PBS_NODEFILE -np $nprocs vasp < INCAR > $nm.stdout

# aprun -n 4 -N 1 -d 32 ~/bin/vasp < INCAR > $nm.stdout
";
